# Generated by Django 4.1.5 on 2023-01-02 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.utils


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=user.utils.get_image_path)),
                ('is_avatar', models.BooleanField(default=False, verbose_name='Main image of profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL, verbose_name='User profile images')),
            ],
        ),
    ]
